import jsPDF from 'jspdf'

export function downloadNotesPdf({ topic, difficulty, notes }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 48
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let y = margin

  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 72, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('AI Student Tutor', margin, 44)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Study Notes', pageWidth - margin, 44, { align: 'right' })

  y = 104
  doc.setTextColor(15, 23, 42)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(topic, margin, y)
  y += 22

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(`Difficulty: ${difficulty}`, margin, y)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin, y, { align: 'right' })
  y += 16
  doc.setDrawColor(226, 232, 240)
  doc.line(margin, y, pageWidth - margin, y)
  y += 24

  doc.setTextColor(15, 23, 42)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Notes', margin, y)
  y += 20

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)

  notes.forEach((note, i) => {
    const bullet = `${i + 1}.`
    const wrapped = doc.splitTextToSize(note, pageWidth - margin * 2 - 24)
    const blockHeight = wrapped.length * 14 + 6
    if (y + blockHeight > pageHeight - margin - 40) {
      addFooter(doc, pageWidth, pageHeight)
      doc.addPage()
      y = margin
    }
    doc.setFont('helvetica', 'bold')
    doc.text(bullet, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.text(wrapped, margin + 24, y)
    y += blockHeight + 4
  })

  addFooter(doc, pageWidth, pageHeight)
  doc.save(`notes-${topic.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}

function addFooter(doc, pageWidth, pageHeight) {
  const margin = 48
  doc.setDrawColor(226, 232, 240)
  doc.line(margin, pageHeight - 56, pageWidth - margin, pageHeight - 56)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text('Generated by AI Student Tutor', margin, pageHeight - 36)
  doc.text(new Date().toLocaleString(), pageWidth - margin, pageHeight - 36, { align: 'right' })
}
